# Site Settings
title:               "Global Language &amp; Culture Strategies"
tagline:             "a LLC"
description:
baseurl:            #"/blog"
url:                #""
github:
  url:               ""
author:
  name:              "Cristen Colleen"
  email:             "GlobalLanguageAndCulture@gmail.com"
paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
