# Site Settings
title:               "Global Language &amp; Culture Strategies"
tagline:             "a LLC"
description:
baseurl:            #"https://jeffchang5.github.io/Global-Language-and-Culture/"
url:                #""
github:
  url:               "https://jeffchang5.github.io/Global-Language-and-Culture/"
author:
  name:              "Cristen Colleen"
  email:             "GlobalLanguageAndCulture@gmail.com"
paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
